In [ ]:
#2a self attention
import torch
import torch.nn.functional as F
# Read sentence from user
sentence = input("Enter a sentence: ")
# Split sentence into words
tokens = sentence.split()
# Generate random embeddings for tokens
embeddings = torch.rand(len(tokens), 8)
# Assign embeddings as Query, Key, and Value
Q = embeddings
K = embeddings
V = embeddings
# Compute attention score matrix
scores = torch.matmul(Q, K.T)
# Convert scores into attention weights
weights = F.softmax(scores, dim=1)
# Compute context vectors
context = torch.matmul(weights, V)
# Display attention scores
print("\nAttention Scores:")
print(scores)
# Display attention weights
print("\nAttention Weights:")
print(weights)
# Display context vector for each word
print("\nContext Vectors:")
for i in range(len(tokens)):
    print("Context vector for", tokens[i], ":")
    print(context[i])

Enter a sentence:  implement and visualize the self-attention

Attention Scores:
tensor([[3.2309, 2.3598, 2.2143, 1.4250, 1.6198],
        [2.3598, 2.2646, 1.7407, 1.5350, 1.5737],
        [2.2143, 1.7407, 2.0908, 0.8100, 1.3129],
        [1.4250, 1.5350, 0.8100, 1.8287, 0.9937],
        [1.6198, 1.5737, 1.3129, 0.9937, 1.5282]])

Attention Weights:
tensor([[0.4664, 0.1952, 0.1687, 0.0766, 0.0931],
        [0.2993, 0.2721, 0.1611, 0.1312, 0.1363],
        [0.3166, 0.1972, 0.2799, 0.0777, 0.1286],
        [0.2082, 0.2324, 0.1125, 0.3117, 0.1352],
        [0.2417, 0.2308, 0.1778, 0.1292, 0.2205]])

Context Vectors:
Context vector for implement :
tensor([0.4195, 0.7229, 0.1106, 0.4035, 0.6110, 0.6311, 0.6922, 0.2507])
Context vector for and :
tensor([0.3366, 0.7045, 0.1426, 0.3569, 0.4938, 0.6312, 0.6435, 0.3254])
Context vector for visualize :
tensor([0.3793, 0.7456, 0.1149, 0.4192, 0.5391, 0.5423, 0.6438, 0.2860])
Context vector for the :
tensor([0.2529, 0.5848, 0.2197, 0.2913, 0.4185, 

In [ ]:
#2b multi head attention
import torch
import torch.nn.functional as F
# Input sentence
sentence = input("Enter a sentence: ")
# Tokenize sentence
tokens = sentence.split()
# Create embeddings
embeddings = torch.rand(len(tokens), 8)
# Number of attention heads
heads = 2
head_size = embeddings.size(1) // heads
# Apply attention for each head
for h in range(heads):
    print("\n========== Head", h + 1, "==========")
    # Split embeddings for current head
    Q = embeddings[:, h*head_size:(h+1)*head_size]
    K = Q
    V = Q
    # Compute attention scores
    scores = torch.matmul(Q, K.T)
    # Normalize scores
    weights = F.softmax(scores, dim=1)
    # Compute context vectors
    context = torch.matmul(weights, V)
    print("\nAttention Scores:")
    print(scores)
    print("Attention Weights:")
    print(weights)
    print("Context Vectors:")
    for i in range(len(tokens)):
        print("Context vector for", tokens[i], "(Head", h + 1, "):")
        print(context[i])


Enter a sentence: implement and visualize the self-attention

========== Head 1 ==========

Attention Scores:
tensor([[0.7635, 0.8743, 0.4070, 0.4805, 0.4366],
        [0.8743, 1.1107, 0.3921, 0.3841, 0.6614],
        [0.4070, 0.3921, 0.6678, 0.5614, 0.3520],
        [0.4805, 0.3841, 0.5614, 0.7479, 0.1520],
        [0.4366, 0.6614, 0.3520, 0.1520, 0.6195]])
Attention Weights:
tensor([[0.2330, 0.2603, 0.1631, 0.1756, 0.1680],
        [0.2323, 0.2942, 0.1434, 0.1423, 0.1878],
        [0.1853, 0.1826, 0.2405, 0.2162, 0.1754],
        [0.1992, 0.1809, 0.2160, 0.2603, 0.1435],
        [0.1952, 0.2444, 0.1793, 0.1468, 0.2343]])
Context Vectors:
Context vector for implement (Head 1 ):
tensor([0.4460, 0.3164, 0.4857, 0.1931])
Context vector for and (Head 1 ):
tensor([0.4216, 0.3278, 0.5242, 0.1813])
Context vector for visualize (Head 1 ):
tensor([0.4646, 0.3239, 0.3889, 0.2302])
Context vector for the (Head 1 ):
tensor([0.4947, 0.3021, 0.3818, 0.2234])
Context vector for self-attention (Head 