<a href="https://colab.research.google.com/github/poojitha-135/LLM/blob/main/input_pipeline(llm).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
# Step 1: Tokenization
sentence = "Architectures in a llm"
tokens = sentence.split()
print("Step 1: Tokens")
print(tokens)
# Step 2: Token IDs
vocab = {token: idx for idx, token in enumerate(tokens)}
token_ids = torch.tensor([vocab[token] for token in tokens])
print("\nStep 2: Token IDs")
for token, idx in vocab.items():
    print(f"{token} → {idx}")
# Step 3: Token Embeddings
embedding_dim = 8
token_embedding_layer = nn.Embedding(len(vocab), embedding_dim)
token_embeddings = token_embedding_layer(token_ids)
print("\nStep 3: Token Embeddings")
for token, emb in zip(tokens, token_embeddings):
    print(f"\n{token} token embedding:\n{emb}")
# Step 4: Positional Embeddings
max_len = len(tokens)
position_ids = torch.arange(max_len)
positional_embedding_layer = nn.Embedding(max_len, embedding_dim)
positional_embeddings = positional_embedding_layer(position_ids)
print("\nStep 4: Positional Embeddings")
for i, pos_emb in enumerate(positional_embeddings):
    print(f"\nPosition {i} embedding:\n{pos_emb}")
# Step 5: Final Input Vectors
# (Token Embedding + Positional Embedding)
final_input_vectors = token_embeddings + positional_embeddings
print("\nStep 5: Final Input Vectors (Token + Position)")
for token, final_vec in zip(tokens, final_input_vectors):
    print(f"\nFinal input vector for '{token}':\n{final_vec}")

Step 1: Tokens
['Architectures', 'in', 'a', 'llm']

Step 2: Token IDs
Architectures → 0
in → 1
a → 2
llm → 3

Step 3: Token Embeddings

Architectures token embedding:
tensor([ 1.5753,  0.9956, -0.4382, -0.8278,  0.1510, -0.0030, -1.3857, -0.0956],
       grad_fn=<UnbindBackward0>)

in token embedding:
tensor([ 1.1817,  0.5014, -1.0012, -0.5865,  0.0785, -1.3120,  0.4565, -0.6219],
       grad_fn=<UnbindBackward0>)

a token embedding:
tensor([ 0.2597,  0.1420, -2.1856, -0.2566,  2.9763,  2.7537, -0.1780,  0.2411],
       grad_fn=<UnbindBackward0>)

llm token embedding:
tensor([ 0.5663,  1.2422,  0.7175,  0.2247, -0.2903, -0.4005, -1.3815, -1.5078],
       grad_fn=<UnbindBackward0>)

Step 4: Positional Embeddings

Position 0 embedding:
tensor([-1.2337,  2.2709, -0.2260, -0.8339,  0.0372, -0.3234, -0.2746, -1.0020],
       grad_fn=<UnbindBackward0>)

Position 1 embedding:
tensor([ 0.6856, -0.1911, -0.4081,  0.1439,  0.3352,  1.3068,  1.4433, -1.1544],
       grad_fn=<UnbindBackward0>)

Po

In [ ]:
input